### PR TITLE
Ensure plugin attributes become properties

### LINKED ISSUE #7: BadRequest: Invalid or duplicate property id errors for all Plone requests
I'm getting errors for all requests being sent to Plone objects upon upgrading from v1.x to v2.0 for me on Plone 4.3.7:

```
2016-01-21 17:54:55 ERROR Zope.SiteErrorLog
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 607, in traverse
  Module Products.PluggableAuthService.PluggableAuthService, line 244, in validate
  Module Products.PluggableAuthService.PluggableAuthService, line 605, in _extractUserIds
  Module Products.AutoUserMakerPASPlugin.auth, line 515, in extractCredentials
  Module Products.AutoUserMakerPASPlugin.auth, line 368, in getConfig
  Module OFS.PropertyManager, line 285, in manage_addProperty
  Module OFS.PropertyManager, line 184, in _setProperty
BadRequest: Invalid or duplicate property id
```

[This](https://github.com/collective/Products.AutoUserMakerPASPlugin/blame/master/Products/AutoUserMakerPASPlugin/auth.py#L366) is where the issue is occurring.  The properties are attributes on the AutoUserMakerPASPlugin object (eg `hasattr(self, prop[0])` return true), but `self.propertyIds()` returns only `['prefix']`, so the code attempts to add the property anyway.

I'm not familiar with the Zope internals here beyond reading the PropertyManager.py (https://github.com/zopefoundation/Zope/blob/master/src/OFS/PropertyManager.py) -- which seems to put all properties into `self._properties` and also as object attributes.  In my case, my existing plugin has the latter but not the former.

@tomgross, would this pull request in #8 be suitable as a fix?

### PR DESCRIPTION
**Pull request by davidjb**
Fixes #7, but needs review.

### CODE REVIEW

**Comment by tomgross** [comment]
Hi @davidjb . Thanks for the patch! Does https://github.com/collective/Products.AutoUserMakerPASPlugin/commit/84f05584067c16d8d492e77f69e9c27848f638b2 work for you too? I prefer this since it is better readble.

**Comment by tomgross** [comment]
merged via cherry pick. @davidjb your solution was correct :-)

**Comment by davidjb** [comment]
@tomgross Was was the issue with your commit? Yours looked a lot simpler; I'd just followed the core of PropertyManager from Zope.

**Comment by tomgross** [comment]
@davidjb The issue with my commit was that the check was on a high level (PropertyManager) and not low level (Python attribute) and was therefore wrong.

**Pull request closed without merging**
