### PR TITLE
Skip CSRF Protection When Updating User

### PR DESCRIPTION
**Pull request by sebasgo**
Plone's automatic CSRF protection doesn't allow write transactions without a token. Which we don't have all the time when logging in via Shibboleth, which can happen anytime for any request. So mark the changed objects as safe to write to.

### CODE REVIEW

**Comment by tomgross** [comment]
@sebasgo Thanks for the patch! Wouldn't it be sufficient to provide _IDisableCSRFProtection_ in case the properties are written. This is less intrusive and probably also more readable.

**Comment by sebasgo** [comment]
I agree that using `IDisableCSRFProtection` would be sufficient, more readable and less intrusive, but also less secure. I would disable the protection for the whole request. Which could be basically any request including requests which have other side effects the CSRF protection wants to guard. This makes the extra code and complexity worthwhile to me. I think `IDisableCSRFProtection` is fine for specific browser views (like the the image scaling view), but here I would really would like to avoid it.

We also tried to use `safeWrite` without recording the changed objects, but this was even more difficult. The user properties are stored in a `OOBTree` and there is no API to get the dirty bucket bucket list. 

In the end I you decision. If you don't want to have this solution I propose a submit using `IDisableCSRFProtection` 

We have the this patch in [production](https://tu-dresden.de) since three months and had no problems so far.

**Comment by raphael-ritz** [comment]
Whatever the solution will turn out to be I'd just like to add that we are interested in solving this issue as well as it hits us at https://dp.eudat.eu
Quickly browsing through the proposed changes I can't see any immediate issues with the proposed solution but I've not tested the patch for real yet.

**Comment by tomgross** [comment]
I'm convinced :wink: @sebasgo @raphael-ritz do you have any other valuable contributon or shall I cut a release?

**Comment by raphael-ritz** [comment]
A release would be much appreciated here. I've nothing to add except mentioning that some indication to reinstall the plugin, e.g., via a new profile version, would be in order. Not because of this addition but the previous one - the one with the timeout property - which fails as long as you do not reinstall in a site that uses this already. Some more logging at the warning level might even be OK but that's nit-picking.

The only other thing I could think of is more flexibility wrt what properties are offered for the mapping of request parameters to user properties. It may not be uncommon that sites extend the member properties to contain further information from the SAML assertions (like additional ids, distinguished names, level of assurance, ...) - but that's another issue entirely and I don't have any code (yet) implementing this. But if I find some time ... (famous last words) - so stay tuned.

Thanks for a great plugin.

**Comment by sebasgo** [comment]
Thanks for merging my contributions so quickly.

I would appreciate a release, too. I would give us the chance to get rid of our fork of this add-on. At the moment, I have nothing more to contribute. *Products.AutoUserMakerPASPlugin* does now exactly that we need.

**Pull request merged**
